### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by robomentor** [rubickCenter/rubick#111]
项目根目录执行：npm install 报错

> rubick@2.0.4-beta.1 postinstall D:\rubick
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- D:\rubick\node_modules\builder-util\out\fs.js
- D:\rubick\node_modules\builder-util\out\util.js
- D:\rubick\node_modules\electron-builder\out\cli\cli.js
- D:\rubick\node_modules\electron-builder\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\rubick\node_modules\builder-util\src\fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\rubick\node_modules\builder-util\src\util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubick@2.0.4-beta.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubick@2.0.4-beta.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2022-06-07T06_18_20_486Z-debug.log
PS D:\rubick>

**Comment by muwoo** [comment]
@robomentor 更新一下，再试试用 `yarn`
