### ISSUE TITLE
M1安装插件报错

### ISSUE THREAD

**Issue by uweii** [rubickCenter/rubick#130]
Uncaught Exception:
Error: spawn npm ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

**截图**
<img width="260" alt="image" src="https://user-images.githubusercontent.com/27764376/185289289-4be1c09e-1cd7-49e6-b48e-83d163b85b83.png">

**Comment by pansinm** [comment]
linux 也是一样，可以先打开bash，命令行运行rubick，打开后可以正常安装。

**Comment by muwoo** [comment]
@uweii 更新一下最新的安装包，有问题再开吧
