### ISSUE TITLE
arch 包过时的状态，可以更新一下吗

### ISSUE THREAD

**Issue by artillerymans** [rubickCenter/rubick#135]
**描述一下这个bug**
yay -S rubick
 -> 找不到所有需要的包:
	electron11 (被这些包需要: rubick)

**复现方式**

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by TheBinger** [comment]
你可以先通过`yay -S electron11-bin`暂时安装[electron11-bin](https://aur.archlinux.org/packages/electron11-bin)这个包来修复这个问题，不过AUR上的rubick包已经过时了，你可以用[debtap](https://aur.archlinux.org/packages/debtap)来转换deb到pkg来暂时安装rubick：
```
debtap rubick_2.0.4-beta.3_amd64.deb (PS. 我这里会出现依赖clion的情况，需要自己手动去PKGBUILD里删除)
sudo pacman -U <package_name>.pkg
```
希望开发者尽快更新AUR上的包。

**Comment by zhuangzhuang20080802** [comment]
打了一个包[rubick-bin](https://aur.archlinux.org/packages/rubick-bin)

**Comment by nzlov** [comment]
i3 打不开

**Comment by du00cs** [comment]
要不还是先打AppImage，绕开大部分发行版类的问题吧

**Comment by xhuohai** [comment]
> 打了一个包[rubick-bin](https://aur.archlinux.org/packages/rubick-bin) 主要问题是不能自定义快捷键

这个版本打开就卡住

**Comment by fecet** [comment]
[1940817:0907/122317.806268:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[1940817:0907/122317.806280:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
^[ ^@^R
^[ ^@Checking for update
(node:1940817) UnhandledPromiseRejectionWarning: Error: ENOENT, dev-app-update.yml not found in /opt/rubick/app.asar
    at createError (node:electron/js2c/asar_bundle:2:1265)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:2:7709)
    at node:internal/util:375:7
    at new Promise (<anonymous>)
    at fsReadFileAsar (node:internal/util:361:12)
    at Object.readFile (node:electron/js2c/asar_bundle:2:9061)
    at d.loadUpdateConfig (/opt/rubick/app.asar/background.js:2:117302)
    at t.Lazy.<anonymous> (/opt/rubick/app.asar/background.js:2:111267)
    at get value [as value] (/opt/rubick/app.asar/background.js:2:484606)
    at d.getUpdateInfoAndProvider (/opt/rubick/app.asar/background.js:2:115205)
(Use `electron26 --trace-warnings ...` to show where the warning was created)
(node:1940817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

我也出了这个问题

**Comment by zxp19821005** [comment]
@xhuohai 这个包是我打的，现在运行时确实是有问题。
### 运行环境
rubick版本: 4.0.7
OS:EndeavourOS
Kernel:6.1.58-1-lts
DE:Cinnamon 5.8.0-1
### 报错信息
我调用的AUR的`electron26`，打开一会之后就白屏了：
```
$ electron26 src/opt/rubick/resources/app.asar
[267598:1020/122551.771702:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[267598:1020/122551.771735:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[267598:1020/122551.794267:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain._sendInternal (node:electron/js2c/browser_init:2:94829)
    at WebContents._sendInternal (node:electron/js2c/browser_init:2:79846)
    at node:electron/js2c/browser_init:2:107198
    at new Promise (<anonymous>)
    at Object.invokeInWebContents (node:electron/js2c/browser_init:2:106945)
    at WebContents.executeJavaScript (node:electron/js2c/browser_init:2:80714)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain._sendInternal (node:electron/js2c/browser_init:2:94829)
    at WebContents._sendInternal (node:electron/js2c/browser_init:2:79846)
    at node:electron/js2c/browser_init:2:107198
    at new Promise (<anonymous>)
    at Object.invokeInWebContents (node:electron/js2c/browser_init:2:106945)
    at WebContents.executeJavaScript (node:electron/js2c/browser_init:2:80714)
```
使用作者打包好的deb中自带的electron，也是一样的问题。
报错信息如下：
```
$ ./src/opt/rubick/rubick
[266587:1020/121913.520117:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[266587:1020/121913.520154:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain._sendInternal (node:electron/js2c/browser_init:2:94573)
    at WebContents._sendInternal (node:electron/js2c/browser_init:2:79800)
    at node:electron/js2c/browser_init:2:106942
    at new Promise (<anonymous>)
    at Object.invokeInWebContents (node:electron/js2c/browser_init:2:106689)
    at WebContents.executeJavaScript (node:electron/js2c/browser_init:2:80668)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain._sendInternal (node:electron/js2c/browser_init:2:94573)
    at WebContents._sendInternal (node:electron/js2c/browser_init:2:79800)
    at node:electron/js2c/browser_init:2:106942
    at new Promise (<anonymous>)
    at Object.invokeInWebContents (node:electron/js2c/browser_init:2:106689)
    at WebContents.executeJavaScript (node:electron/js2c/browser_init:2:80668)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain._sendInternal (node:electron/js2c/browser_init:2:94573)
    at WebContents._sendInternal (node:electron/js2c/browser_init:2:79800)
    at node:electron/js2c/browser_init:2:106942
    at new Promise (<anonymous>)
    at Object.invokeInWebContents (node:electron/js2c/browser_init:2:106689)
    at WebContents.executeJavaScript (node:electron/js2c/browser_init:2:80668)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by muwoo** [comment]
@zxp19821005 我搞个linux虚拟机调试一下，感谢反馈

**Comment by muwoo** [comment]
@zxp19821005 我的虚拟机环境一直有问题，rubick项目你本地可以帮忙调试一下看看哪里有问题，欢迎PR

**Comment by wind2008hxy** [comment]
@zxp19821005 
1.首先感谢打包aur
2.关于
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
```
尝试使用electron25或者electron27 运行asar

**Comment by wind2008hxy** [comment]
@muwoo see https://github.com/electron/electron/issues/39775#issuecomment-1732114473
可以考虑更新 package.json "electron": "26.0.0",   25.x.x或者27.x.x

**Comment by zxp19821005** [comment]
不知道怎么回事，我今天编译一直在报错，我稍后再试一试。
```
$ yarn   
yarn install v1.22.19
[1/4] Resolving packages...
warning Resolution field "leveldown@6.0.3" is incompatible with requested version "leveldown@5.6.0"
warning Resolution field "leveldown@6.0.3" is incompatible with requested version "leveldown@^5.4.0"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > worker-loader@3.0.8" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "@types/bluebird@*".
warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "@types/node@*".
warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "ts-toolbelt@*".
warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "@types/bluebird@*".
warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "@types/node@*".
warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "ts-toolbelt@^9.6.0".
warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > worker-plugin@5.0.1" has unmet peer dependency "webpack@>= 4".
[4/4] Building fresh packages...
[1/6] ⠁ electron
[-/6] ⠁ waiting...
[3/6] ⠁ extract-file-icon
[-/6] ⠁ waiting...
error /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon: Command failed.
Exit code: 1
Command: npm run rebuild
Arguments: 
Directory: /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon
Output:
> extract-file-icon@0.3.2 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@16.20.2 | linux | x64
gyp info find Python using Python version 3.11.5 found at "/usr/bin/python"
(node:347556) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/zxp-endeavouros/.cache/node-gyp/16.20.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/zxp-endeavouros/.cache/node-gyp/16.20.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/zxp-endeavouros/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 6.1.60-1-lts
gyp ERR! command "/home/zxp-endeavouros/.nvm/versions/node/v16.20.2/bin/node" "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon
```

**Comment by wind2008hxy** [comment]
@zxp19821005 rubick-4.1.0-beta.2 目前我还没有编译安装。

**Comment by muwoo** [comment]
> @muwoo see [electron/electron#39775 (comment)](https://github.com/electron/electron/issues/39775#issuecomment-1732114473) 可以考虑更新 package.json "electron": "26.0.0", 25.x.x或者27.x.x

ok

**Comment by zxp19821005** [comment]
### 使用Electron25运行，点击`系统设置`报错
```
$ rubick
[64855:1101/093741.716199:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[64855:1101/093741.716214:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[64855:1101/093741.761393:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
(node:64855) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/renderer_init:2:17004
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:11193)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9266)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:64855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### 使用Electron27运行，点击`系统设置`报错
```
$ rubick
[61202:1101/093541.093383:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[61202:1101/093541.093406:ERROR:select_file_dialog_linux_portal.cc(280)] Failed to read portal version property
(node:61202) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/renderer_init:2:19335
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:13547)
    at EventEmitter.emit (node:events:514:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:11620)
(Use `electron27 --trace-warnings ...` to show where the warning was created)
(node:61202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by wind2008hxy** [comment]
@zxp19821005 你是在用gnome？系统？检查一下是否有安装xdg-desktop-portal-gtk

**Comment by wind2008hxy** [comment]
> 不知道怎么回事，我今天编译一直在报错，我稍后再试一试。最新的`4.1.1`版本也是一样的。
> 
> ```
> $ yarn   
> yarn install v1.22.19
> [1/4] Resolving packages...
> warning Resolution field "leveldown@6.0.3" is incompatible with requested version "leveldown@5.6.0"
> warning Resolution field "leveldown@6.0.3" is incompatible with requested version "leveldown@^5.4.0"
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> warning " > worker-loader@3.0.8" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
> warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "@types/bluebird@*".
> warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "@types/node@*".
> warning " > @ts-type/package-dts@1.0.60" has unmet peer dependency "ts-toolbelt@*".
> warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "@types/bluebird@*".
> warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "@types/node@*".
> warning "@ts-type/package-dts > ts-type@2.1.8" has unmet peer dependency "ts-toolbelt@^9.6.0".
> warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
> warning " > worker-plugin@5.0.1" has unmet peer dependency "webpack@>= 4".
> [4/4] Building fresh packages...
> [1/6] ⠁ electron
> [-/6] ⠁ waiting...
> [3/6] ⠁ extract-file-icon
> [-/6] ⠁ waiting...
> error /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon: Command failed.
> Exit code: 1
> Command: npm run rebuild
> Arguments: 
> Directory: /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon
> Output:
> > extract-file-icon@0.3.2 rebuild
> > node-gyp rebuild
> 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@5.1.1
> gyp info using node@16.20.2 | linux | x64
> gyp info find Python using Python version 3.11.5 found at "/usr/bin/python"
> (node:347556) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> gyp info spawn /usr/bin/python
> gyp info spawn args [
> gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/zxp-endeavouros/.cache/node-gyp/16.20.2/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/zxp-endeavouros/.cache/node-gyp/16.20.2',
> gyp info spawn args   '-Dnode_gyp_dir=/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/zxp-endeavouros/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> Traceback (most recent call last):
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
>     sys.exit(gyp.script_main())
>              ^^^^^^^^^^^^^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
>     return main(sys.argv[1:])
>            ^^^^^^^^^^^^^^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
>     return gyp_main(args)
>            ^^^^^^^^^^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
>     [generator, flat_list, targets, data] = Load(
>                                             ^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
>     result = gyp.input.Load(build_files, default_variables, includes[:],
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
>     LoadTargetBuildFile(build_file, data, aux_data,
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
>     build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
>     build_file_contents = open(build_file_path, 'rU').read()
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: invalid mode: 'rU' while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
> gyp ERR! System Linux 6.1.60-1-lts
> gyp ERR! command "/home/zxp-endeavouros/.nvm/versions/node/v16.20.2/bin/node" "/home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/.bin/node-gyp" "rebuild"
> gyp ERR! cwd /home/zxp-endeavouros/.cache/paru/clone/rubick/src/rubick-4.1.0-beta.2/node_modules/extract-file-icon
> ```

https://github.com/nodejs/node-gyp/issues/2219
https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp

python版本原因，或者考虑更新node-gyp，参考上面链接。

**Comment by wind2008hxy** [comment]
`export PYTHON=/usr/bin/python3.9 `
正常构建
