### ISSUE TITLE
Frequent error: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by qidian99** [rubickCenter/rubick#185]
**描述一下这个bug**
很多次在输入时 js 抛异常，报错如下：
```js
Uncaught Exception:
TypeError: Cannot read property 'setBounds' of undefined
at Object.<anonymous> (/Applications/rubick2.app/Contents/Resources/app.asar/background.js:2:626528)
at Object.onceWrapper (events.js:422:26)
at Object.emit (events.js:315:20)
```
**复现方式**
这个错误比较频繁，一下午出现十次以上，macos intel （os version 13.6）

**预期行为**
清晰简明地描述了您预期的发生。
不应该有异常

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/rubickCenter/rubick/assets/20527912/2ed7097b-d408-47db-8d36-30b209854e77)

**Comment by ergwang** [comment]
我windows11也有这个问题

**Comment by muwoo** [comment]
@layyback 有空看看是不是这里的问题：
```js
  public windowMoving({ data: { mouseX, mouseY, width, height } }, window, e) {
    const { x, y } = screen.getCursorScreenPoint();
    const originWindow = this.getCurrentWindow(window, e);
    if (!originWindow) return;
    originWindow.setBounds({ x: x - mouseX, y: y - mouseY, width, height });
  }
```
