### ISSUE TITLE
archlinux安装的时候编译失败

### ISSUE THREAD

**Issue by g1fts** [rubickCenter/rubick#248]
编译失败
```bash
==> 正在开始 build()...
node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/stone/.cache/yay/rubick-bin/src/opt/rubick2/resources/app.asar'
    at Object.openSync (node:fs:603:3)
    at module.exports.readArchiveHeaderSync (/usr/lib/node_modules/@electron/asar/lib/disk.js:58:17)
    at module.exports.readFilesystemSync (/usr/lib/node_modules/@electron/asar/lib/disk.js:84:25)
    at module.exports.extractAll (/usr/lib/node_modules/@electron/asar/lib/asar.js:174:27)
    at Command.<anonymous> (/usr/lib/node_modules/@electron/asar/bin/asar.js:72:10)
    at Command.listener [as _actionHandler] (/usr/lib/node_modules/@electron/asar/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/usr/lib/node_modules/@electron/asar/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/usr/lib/node_modules/@electron/asar/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/usr/lib/node_modules/@electron/asar/node_modules/commander/index.js:882:12)
    at Command.parse (/usr/lib/node_modules/@electron/asar/node_modules/commander/index.js:717:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/stone/.cache/yay/rubick-bin/src/opt/rubick2/resources/app.asar'
}

Node.js v18.18.0
==> 错误： 在 build() 中发生一个错误。    正在放弃...
 -> 生成时出错: rubick-bin-exit status 4
 -> 无法安装以下软件包, 需要手动介入处理:
rubick-bin - exit status 4
```

**Comment by muwoo** [comment]
@g1fts 使用最新的代码再试试

**Comment by zxp19821005** [comment]
@g1fts 或者你到 后面可以看到这个错误：
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.18.0"
```
建议你安装一个`nvm`
然后在编译前执行以下命令：
```
nvm install 16
nvm use 16
```
然后再安装试试看。

**Comment by zxp19821005** [comment]
@g1fts 我已经修改了AUR上的`rubick`并提交，后面应该不会编译失败了。建议你重新更新一下。
但是目前版本会运行失败，运行一会之后会白屏，包括已经编译好的AppImage版本。
建议作者最好排查一下。4.0.7版。

**Comment by g1fts** [comment]
> @g1fts 我已经修改了AUR上的`rubick`并提交，后面应该不会编译失败了。建议你重新更新一下。 但是目前版本会运行失败，运行一会之后会白屏，包括已经编译好的AppImage版本。 建议作者最好排查一下。4.0.7版。

我之前作者更新的时候我重新安装过，安装之后点击输入框后面的图像没有任何反应之后，我就给卸载了。后面我因为别的原因把系统给删了，现在没在用arch了。测试不了了。
